import logging
from src.core.state import PipelineGraphState
from src.agents.execution_agent import ExecutionAgent

logger = logging.getLogger(__name__)

def trade_execution_node(state: PipelineGraphState) -> PipelineGraphState:
    """
    Executes the target orders generated by the Portfolio Construction node.
    Uses a Paper Broker for simulation.
    """
    logger.info("--- Node: Trade Execution ---")
    
    orders = state.get('orders', [])
    data = state.get('data', {})
    config = state.get('config', {})
    broker = state.get('broker') # Get injected broker if available
    
    # Initialize Execution Agent
    agent = ExecutionAgent(config=config, broker=broker)
    
    if not orders:
        logger.info("No orders to execute.")
        # Log current portfolio status
        cash = agent.broker.get_cash()
        positions = agent.broker.get_positions()
        logger.info(f"Current Cash: ${cash:,.2f}")
        logger.info(f"Current Positions: {positions}")
        
        state['execution_results'] = []
        return state
    
    # Execute Orders
    results = agent.execute_orders(orders, data)
    
    # Update State
    state['execution_results'] = results
    
    logger.info(f"Execution Completed. {len(results)} orders processed.")
    
    return state


from .execution_nodes import forecasting_node
